some_long_articles = [
    "List of Glagolitic manuscripts",
    "List of Statutory Rules and Orders of Northern Ireland",
    "Berliner FC Dynamo",
    "Tawag ng Tanghalan (season 6)",
    "List of Hindi songs recorded by Asha Bhosle",
    "Municipal history of Quebec",
    "List of battles by geographic location",
    "List of Gunsmoke (TV series) episodes",
    "Tartan",
    "List of 2021–22 NBA season transactions",
    "List of common misconceptions",
    "2022 in science",
    "2022 in video games",
    "Opinion polling for the 2015 United Kingdom general election",
    "Nationwide opinion polling for the 2016 United States presidential election",
    "Opinion polling for the next United Kingdom general election",
    "Criminal proceedings in the January 6 United States Capitol attack",
    "List of countries by life expectancy",
    "List of canonically crowned images",
    "2021–22 Liga IV",
    "List of dynasties",
    "Presidency of Rodrigo Duterte",
    "Glossary of baseball terms",
    "Presidency of Donald Trump",
    "List of organisms named after famous people (born 1900–1949)",
    "Sixth Labour Government of New Zealand",
    "2022 in American television",
    "2022–23 Liga IV",
    "2012 in science",
    "2021 in American television",
    "List of suicides",
    "List of chess grandmasters",
    "Results of the 1997 United Kingdom general election by constituency",
    "List of apple cultivars",
    "1922 regnal list of Ethiopia",
    "List of Project EGG games",
    "List of other classes of keelboats & yachts",
    "2022 Houston Astros season",
    "Opinion polling for the 2023 Polish parliamentary election",
    "Timeline of women's legal rights (other than voting) in the 20th century",
    "List of NCAA Division I conference changes since 2010",
    "Attempts to overturn the 2020 United States presidential election",
    "2022–23 Arsenal F.C. season",
    "COVID-19 pandemic in the Czech Republic",
    "List of solved missing person cases: pre-2000",
    "Timeline of LGBT history, 21st century",
    "Intercollegiate sports team champions",
    "2020 United States House of Representatives elections in Texas",
    "List of Indo-European languages",
    "Joe Gibbs Racing",
    "Amusement Today",
    "List of individuals nominated for the Nobel Peace Prize",
    "Statistics of the COVID-19 pandemic in Chile",
    "List of The Ring pound for pound rankings",
    "List of Dragons' Den (British TV programme) offers Series 11-20",
    "2020 United States House of Representatives elections in California",
    "COVID-19 vaccination in Bulgaria",
    "2022 United States House of Representatives elections in New York",
    "List of organisms named after famous people (born 1800–1899)",
    "2022 United States House of Representatives elections in California",
    "List of attacks related to secondary schools",
    "Opinion polling for the 2022 Italian general election",
    "Nationwide opinion polling for the 2023 Spanish general election (2019–2021)",
    "United Russia",
    "History of AEK Athens F.C.",
    "2022 UCI Mountain Bike season",
    "Boris Johnson",
    "List of people from Illinois",
    "2023 Nigerian presidential election",
    "List of Pan American medalists for Brazil",
    "2022–23 UCI Track Cycling season",
    "List of film director and composer collaborations",
    "List of Supernatural and The Winchesters characters",
    "List of March for Our Lives locations",
    "List of Falcon 9 and Falcon Heavy launches",
    "Steele dossier",
    "List of White Pass and Yukon Route locomotives and cars",
    "List of The Amazing Spider-Man issues",
    "List of federal political scandals in the United States",
    "2023 in video games",
    "COVID-19 pandemic in Oregon",
    "Timeline of 1960s counterculture",
    "List of municipalities in Michigan",
    "Honorific nicknames in popular music",
    "List of largest oil and gas companies by revenue",
    "List of characters in mythology novels by Rick Riordan",
    "List of 2021 Women's March locations",
    "List of 2019 albums",
    "List of Nvidia graphics processing units",
    "2023 in American television",
    "List of observatory codes",
    "2018 in paleontology",
    "List of films based on actual events (before 2000)",
    "2019 Canadian federal election",
    "List of The George Burns and Gracie Allen Show episodes",
    "Reactions to the death of Elizabeth II",
    "List of equipment of the Armed Forces of Ukraine",
    "List of kidnappings",
    "Timeline of women's legal rights (other than voting)",
    "List of University of Pennsylvania people",
    "2020 United States presidential election",
    "2017 in American television",
    "Opinion polling for the 2018 Italian general election",
    "European Cup and UEFA Champions League records and statistics",
    "List of law enforcement officers killed in the line of duty in the United States",
    "2012 in American television",
    "Sexton Blake bibliography part 2: 1912-1945",
    "List of Dragons' Den (British TV programme) offers Series 1-10",
    "List of 2022–23 NBA season transactions",
    "List of Joe Biden 2020 presidential campaign endorsements",
    "COVID-19 pandemic in the State of Palestine",
    "List of events named massacres",
    "United States Army Futures Command",
    "Philippines",
    "Citizenship Amendment Act protests",
    "2018 in American television",
    "List of people and organizations sanctioned during the Russo-Ukrainian War",
    "Donald Trump",
    "List of unarmed African Americans killed by law enforcement officers in the United States",
    "Opinion polling for the 2021 German federal election",
    "Tom Brady",
    "List of In Our Time programmes",
    "List of Huguenots",
    "List of Agents of S.H.I.E.L.D. characters",
    "List of Everybody, Sing! episodes",
    "Great Britain at the Olympics",
    "2019 in paleontology",
    "List of career achievements by Cristiano Ronaldo",
    "List of doping cases in athletics",
    "List of Frontline (American TV program) episodes",
    "2018 in paleomammalogy",
    "List of cities by sunshine duration",
    "2020 in the United Kingdom",
    "List of The Nature of Things episodes",
    "List of mass shootings in the United States in 2022",
    "Hendrick Motorsports in the NASCAR Cup Series",
    "DC Extended Universe",
    "2022 United States House of Representatives elections in Florida",
    "List of Advanced Dungeons & Dragons 2nd edition monsters",
    "List of unsolved murders in the United Kingdom (2000–present)",
    "RFK Racing in the NASCAR Cup Series",
    "Statistics of the COVID-19 pandemic in Peru",
    "Same-sex union legislation",
    "List of Hallmark Channel Original Movies",
    "Opinion polling in United Kingdom constituencies (2010–2015)",
    "List of Android smartphones",
    "List of Philippine laws",
    "List of Intel Core processors",
    "List of RKO Pictures films",
    "List of cities by average precipitation",
    "New York City",
    "Opinion polling for the 2018 Hungarian parliamentary election",
    "List of organisms named after famous people (born before 1800)",
    "List of giant squid specimens and sightings",
    "List of executive actions by George W. Bush",
    "List of executive actions by Franklin D. Roosevelt",
    "2021 New York City Council election",
    "1917 New Year Honours",
    "Pakistan",
    "2015 in British television",
    "List of submarines of World War II",
    "Reorganization plan of United States Army",
    "Vladimir Putin",
    "List of Spanish football transfers summer 2017",
    "Maximilian I, Holy Roman Emperor",
    "Marvel Cinematic Universe",
    "2020 in Mexico",
    "List of serial killers in the United States",
    "List of Deadliest Catch episodes",
    "2022 Cronulla-Sutherland Sharks season",
    "Pre-2016 statewide opinion polling for the 2016 United States presidential election",
    "List of PlayStation 4 games (A–L)",
    "2017–18 ISU World Standings",
    "1st Supreme People's Assembly of North Korea",
    "List of members of the 19th Bundestag",
    "2018 United States House of Representatives elections in California",
    "Trump–Ukraine scandal",
    "2016 United States presidential election",
    "List of third party performances in United States House elections",
    "List of German Americans",
    "2000s",
    "List of giant squid specimens and sightings (2001–2014)",
    "2023 in sports",
    "List of Crayon Shin-chan episodes (1992–2001)",
    "New York Yankees",
    "List of sources for the Crusades",
    "List of Nova episodes",
    "Sub-national opinion polling for the April 2019 Spanish general election",
    "Orson Welles radio credits",
    "History of Mexican Americans",
    "Opinion polling for the 2023 Spanish general election",
    "National University of San Marcos",
    "Aircraft in fiction",
    "List of baritones in non-classical music",
    "List of 2019–20 NBA season transactions",
    "1943 Birthday Honours",
    "List of neighborhoods in South Korea",
    "List of 2016–17 NBA season transactions",
    "Donald Trump 2016 presidential campaign",
    "Tawag ng Tanghalan (season 4)",
    "List of films considered the worst",
    "List of association football families",
    "LGBT rights in the United States",
    "List of people who died in traffic collisions",
    "List of the youngest state legislators in the United States",
    "Varèse Sarabande albums discography",
    "2020 United States House of Representatives elections in New York",
    "NCAA Division I baseball tournament",
    "List of Georgetown University alumni",
    "List of sovereign states by date of formation",
    "2015 in aviation",
    "List of visible minority politicians in Canada",
    "Largest prehistoric animals",
    "List of school shootings in the United States (2000–present)",
    "List of 2014–15 Super Rugby transfers",
    "Topical timeline of Russian interference in the 2016 United States elections",
    "United States House Select Committee on the January 6 Attack",
    "List of Puerto Ricans",
    "2018 Illinois House of Representatives election",
    "Portuguese people",
    "Israel",
    "2015 in American television",
    "Prelude to the Russian invasion of Ukraine",
    "Flora of Malta",
    "List of active United States Air Force aircraft squadrons",
    "History of Australia",
    "Timeline of the Israeli–Palestinian conflict in 2016",
    "List of least concern birds",
    "List of 2018–19 NBA season transactions",
    "Statewide opinion polling for the 2008 United States presidential election",
    "List of current members of the British Privy Council",
    "List of stage names",
    "List of The Loud House episodes",
    "Jeremy Corbyn",
    "List of awards and nominations received by Beyoncé",
    "List of Italian football transfers summer 2016",
    "List of organisms named after famous people (born 1950–present)",
    "List of men's footballers with 1,000 or more official appearances",
    "Paleobiota of the Posidonia Shale",
    "List of Portuguese wine grape varieties",
    "List of accidents and incidents involving military aircraft (1955–1959)",
    "Lionel Messi",
    "List of shipwrecks in 1819",
    "2020–2021 China–India skirmishes",
    "Taikyoku shogi",
    "List of The Best Show with Tom Scharpling episodes",
    "Cristiano Ronaldo",
    "Timeline of the Bill Clinton presidency (1998)",
    "Sub-national opinion polling for the 2011 Spanish general election",
    "2020–2022 Malaysian political crisis"
]
