many_long_articles = [
    "List of Glagolitic manuscripts",
    "List of Statutory Rules and Orders of Northern Ireland",
    "Berliner FC Dynamo",
    "Tawag ng Tanghalan (season 6)",
    "List of Hindi songs recorded by Asha Bhosle",
    "Municipal history of Quebec",
    "List of battles by geographic location",
    "List of Gunsmoke (TV series) episodes",
    "Tartan",
    "List of 2021–22 NBA season transactions",
    "List of common misconceptions",
    "2022 in science",
    "2022 in video games",
    "Opinion polling for the 2015 United Kingdom general election",
    "Nationwide opinion polling for the 2016 United States presidential election",
    "Opinion polling for the next United Kingdom general election",
    "Criminal proceedings in the January 6 United States Capitol attack",
    "List of countries by life expectancy",
    "List of canonically crowned images",
    "2021–22 Liga IV",
    "List of dynasties",
    "Presidency of Rodrigo Duterte",
    "Glossary of baseball terms",
    "Presidency of Donald Trump",
    "List of organisms named after famous people (born 1900–1949)",
    "Sixth Labour Government of New Zealand",
    "2022 in American television",
    "2022–23 Liga IV",
    "2012 in science",
    "2021 in American television",
    "List of suicides",
    "List of chess grandmasters",
    "Results of the 1997 United Kingdom general election by constituency",
    "List of apple cultivars",
    "1922 regnal list of Ethiopia",
    "List of Project EGG games",
    "List of other classes of keelboats & yachts",
    "2022 Houston Astros season",
    "Opinion polling for the 2023 Polish parliamentary election",
    "Timeline of women's legal rights (other than voting) in the 20th century",
    "List of NCAA Division I conference changes since 2010",
    "Attempts to overturn the 2020 United States presidential election",
    "2022–23 Arsenal F.C. season",
    "COVID-19 pandemic in the Czech Republic",
    "List of solved missing person cases: pre-2000",
    "Timeline of LGBT history, 21st century",
    "Intercollegiate sports team champions",
    "2020 United States House of Representatives elections in Texas",
    "List of Indo-European languages",
    "Joe Gibbs Racing",
    "Amusement Today",
    "List of individuals nominated for the Nobel Peace Prize",
    "Statistics of the COVID-19 pandemic in Chile",
    "List of The Ring pound for pound rankings",
    "List of Dragons' Den (British TV programme) offers Series 11-20",
    "2020 United States House of Representatives elections in California",
    "COVID-19 vaccination in Bulgaria",
    "2022 United States House of Representatives elections in New York",
    "List of organisms named after famous people (born 1800–1899)",
    "2022 United States House of Representatives elections in California",
    "List of attacks related to secondary schools",
    "Opinion polling for the 2022 Italian general election",
    "Nationwide opinion polling for the 2023 Spanish general election (2019–2021)",
    "United Russia",
    "History of AEK Athens F.C.",
    "2022 UCI Mountain Bike season",
    "Boris Johnson",
    "List of people from Illinois",
    "2023 Nigerian presidential election",
    "List of Pan American medalists for Brazil",
    "2022–23 UCI Track Cycling season",
    "List of film director and composer collaborations",
    "List of Supernatural and The Winchesters characters",
    "List of March for Our Lives locations",
    "List of Falcon 9 and Falcon Heavy launches",
    "Steele dossier",
    "List of White Pass and Yukon Route locomotives and cars",
    "List of The Amazing Spider-Man issues",
    "List of federal political scandals in the United States",
    "2023 in video games",
    "COVID-19 pandemic in Oregon",
    "Timeline of 1960s counterculture",
    "List of municipalities in Michigan",
    "Honorific nicknames in popular music",
    "List of largest oil and gas companies by revenue",
    "List of characters in mythology novels by Rick Riordan",
    "List of 2021 Women's March locations",
    "List of 2019 albums",
    "List of Nvidia graphics processing units",
    "2023 in American television",
    "List of observatory codes",
    "2018 in paleontology",
    "List of films based on actual events (before 2000)",
    "2019 Canadian federal election",
    "List of The George Burns and Gracie Allen Show episodes",
    "Reactions to the death of Elizabeth II",
    "List of equipment of the Armed Forces of Ukraine",
    "List of kidnappings",
    "Timeline of women's legal rights (other than voting)",
    "List of University of Pennsylvania people",
    "2020 United States presidential election",
    "2017 in American television",
    "Opinion polling for the 2018 Italian general election",
    "European Cup and UEFA Champions League records and statistics",
    "List of law enforcement officers killed in the line of duty in the United States",
    "2012 in American television",
    "Sexton Blake bibliography part 2: 1912-1945",
    "List of Dragons' Den (British TV programme) offers Series 1-10",
    "List of 2022–23 NBA season transactions",
    "List of Joe Biden 2020 presidential campaign endorsements",
    "COVID-19 pandemic in the State of Palestine",
    "List of events named massacres",
    "United States Army Futures Command",
    "Philippines",
    "Citizenship Amendment Act protests",
    "2018 in American television",
    "List of people and organizations sanctioned during the Russo-Ukrainian War",
    "Donald Trump",
    "List of unarmed African Americans killed by law enforcement officers in the United States",
    "Opinion polling for the 2021 German federal election",
    "Tom Brady",
    "List of In Our Time programmes",
    "List of Huguenots",
    "List of Agents of S.H.I.E.L.D. characters",
    "List of Everybody, Sing! episodes",
    "Great Britain at the Olympics",
    "2019 in paleontology",
    "List of career achievements by Cristiano Ronaldo",
    "List of doping cases in athletics",
    "List of Frontline (American TV program) episodes",
    "2018 in paleomammalogy",
    "List of cities by sunshine duration",
    "2020 in the United Kingdom",
    "List of The Nature of Things episodes",
    "List of mass shootings in the United States in 2022",
    "Hendrick Motorsports in the NASCAR Cup Series",
    "DC Extended Universe",
    "2022 United States House of Representatives elections in Florida",
    "List of Advanced Dungeons & Dragons 2nd edition monsters",
    "List of unsolved murders in the United Kingdom (2000–present)",
    "RFK Racing in the NASCAR Cup Series",
    "Statistics of the COVID-19 pandemic in Peru",
    "Same-sex union legislation",
    "List of Hallmark Channel Original Movies",
    "Opinion polling in United Kingdom constituencies (2010–2015)",
    "List of Android smartphones",
    "List of Philippine laws",
    "List of Intel Core processors",
    "List of RKO Pictures films",
    "List of cities by average precipitation",
    "New York City",
    "Opinion polling for the 2018 Hungarian parliamentary election",
    "List of organisms named after famous people (born before 1800)",
    "List of giant squid specimens and sightings",
    "List of executive actions by George W. Bush",
    "List of executive actions by Franklin D. Roosevelt",
    "2021 New York City Council election",
    "1917 New Year Honours",
    "Pakistan",
    "2015 in British television",
    "List of submarines of World War II",
    "Reorganization plan of United States Army",
    "Vladimir Putin",
    "List of Spanish football transfers summer 2017",
    "Maximilian I, Holy Roman Emperor",
    "Marvel Cinematic Universe",
    "2020 in Mexico",
    "List of serial killers in the United States",
    "List of Deadliest Catch episodes",
    "2022 Cronulla-Sutherland Sharks season",
    "Pre-2016 statewide opinion polling for the 2016 United States presidential election",
    "List of PlayStation 4 games (A–L)",
    "2017–18 ISU World Standings",
    "1st Supreme People's Assembly of North Korea",
    "List of members of the 19th Bundestag",
    "2018 United States House of Representatives elections in California",
    "Trump–Ukraine scandal",
    "2016 United States presidential election",
    "List of third party performances in United States House elections",
    "List of German Americans",
    "2000s",
    "List of giant squid specimens and sightings (2001–2014)",
    "2023 in sports",
    "List of Crayon Shin-chan episodes (1992–2001)",
    "New York Yankees",
    "List of sources for the Crusades",
    "List of Nova episodes",
    "Sub-national opinion polling for the April 2019 Spanish general election",
    "Orson Welles radio credits",
    "History of Mexican Americans",
    "Opinion polling for the 2023 Spanish general election",
    "National University of San Marcos",
    "Aircraft in fiction",
    "List of baritones in non-classical music",
    "List of 2019–20 NBA season transactions",
    "1943 Birthday Honours",
    "List of neighborhoods in South Korea",
    "List of 2016–17 NBA season transactions",
    "Donald Trump 2016 presidential campaign",
    "Tawag ng Tanghalan (season 4)",
    "List of films considered the worst",
    "List of association football families",
    "LGBT rights in the United States",
    "List of people who died in traffic collisions",
    "List of the youngest state legislators in the United States",
    "Varèse Sarabande albums discography",
    "2020 United States House of Representatives elections in New York",
    "NCAA Division I baseball tournament",
    "List of Georgetown University alumni",
    "List of sovereign states by date of formation",
    "2015 in aviation",
    "List of visible minority politicians in Canada",
    "Largest prehistoric animals",
    "List of school shootings in the United States (2000–present)",
    "List of 2014–15 Super Rugby transfers",
    "Topical timeline of Russian interference in the 2016 United States elections",
    "United States House Select Committee on the January 6 Attack",
    "List of Puerto Ricans",
    "2018 Illinois House of Representatives election",
    "Portuguese people",
    "Israel",
    "2015 in American television",
    "Prelude to the Russian invasion of Ukraine",
    "Flora of Malta",
    "List of active United States Air Force aircraft squadrons",
    "History of Australia",
    "Timeline of the Israeli–Palestinian conflict in 2016",
    "List of least concern birds",
    "List of 2018–19 NBA season transactions",
    "Statewide opinion polling for the 2008 United States presidential election",
    "List of current members of the British Privy Council",
    "List of stage names",
    "List of The Loud House episodes",
    "Jeremy Corbyn",
    "List of awards and nominations received by Beyoncé",
    "List of Italian football transfers summer 2016",
    "List of organisms named after famous people (born 1950–present)",
    "List of men's footballers with 1,000 or more official appearances",
    "Paleobiota of the Posidonia Shale",
    "List of Portuguese wine grape varieties",
    "List of accidents and incidents involving military aircraft (1955–1959)",
    "Lionel Messi",
    "List of shipwrecks in 1819",
    "2020–2021 China–India skirmishes",
    "Taikyoku shogi",
    "List of The Best Show with Tom Scharpling episodes",
    "Cristiano Ronaldo",
    "Timeline of the Bill Clinton presidency (1998)",
    "Sub-national opinion polling for the 2011 Spanish general election",
    "2020–2022 Malaysian political crisis",
    "Glossary of geography terms",
    "List of tallest buildings and structures in the Birmingham Metropolitan Area, West Midlands",
    "List of One Piece characters",
    "Leadership approval opinion polling for the next United Kingdom general election",
    "List of NBA players born outside the United States",
    "Historical list of the Catholic bishops of the United States",
    "2017 Rugby Challenge",
    "List of shipwrecks in 1814",
    "List of Doctor Who home video releases",
    "Opinion polling for the April 2019 Spanish general election",
    "List of 2020 albums",
    "List of PlayStation 4 games (M–Z)",
    "List of Hull F.C. players",
    "2021 in paleomammalogy",
    "List of Jewish actors",
    "List of shipwrecks in 1815",
    "List of topics characterized as pseudoscience",
    "2021 in association football",
    "Timeline of the Syrian civil war",
    "List of shipwrecks in 1818",
    "2019 in American television",
    "List of human transcription factors",
    "Republican Party (United States)",
    "List of destroyers of World War II",
    "Constituency election results in the 1929 United Kingdom general election",
    "Richard Childress Racing in the NASCAR Cup Series",
    "List of the winning political parties in the Malaysian general election by parliamentary constituency",
    "2020 Illinois House of Representatives election",
    "2022 in sports",
    "List of Olympic champions in men's water polo",
    "List of doping cases in cycling",
    "Results of the 2010 United Kingdom general election",
    "Italy",
    "List of United Kingdom Parliament constituencies (1885–1918) by region",
    "Russian interference in the 2016 United States elections",
    "List of Freedom of the City recipients (military)",
    "War in Donbas (2014–2022)",
    "2016 in video games",
    "List of Unsolved Mysteries episodes",
    "Texas Longhorns men's basketball",
    "List of constituencies of the National Assembly of France",
    "Results of the 2015 United Kingdom general election",
    "Features of the Marvel Cinematic Universe",
    "List of Chinese monarchs",
    "January 6 United States Capitol attack",
    "List of Ironman Heavymetalweight Champions",
    "2022 United States House of Representatives elections",
    "Statewide opinion polling for the 2016 Republican Party presidential primaries",
    "Royal Space Force: The Wings of Honnêamise",
    "Pennridge–Quakertown Thanksgiving Day Football Classic",
    "List of EastEnders characters (2017)",
    "List of nominees for the Nobel Prize in Literature",
    "Ricky Martin",
    "Foreign policy of the Donald Trump administration",
    "Timeline of the Second Libyan Civil War",
    "2018 Rugby Challenge",
    "List of tenors in non-classical music",
    "List of Magpakailanman episodes",
    "List of ship launches in 1944",
    "2013–14 ISU World Standings and Season's World Ranking",
    "2016 United States Senate elections",
    "Results of the 2017 United Kingdom general election",
    "List of Sites of Special Scientific Interest in Norfolk",
    "New York City directories",
    "List of enclaves and exclaves",
    "Index of Singapore-related articles",
    "List of contemporary ethnic groups",
    "2022 United States House of Representatives elections in Texas",
    "Miss Grand International",
    "2022 deaths in the United States (July–December)",
    "2014 in American television",
    "Timeline of the COVID-19 pandemic in Indonesia (2021)",
    "2010s",
    "List of serial killers by country",
    "Immortal Songs: Singing the Legend",
    "Women in Islam",
    "List of English translations from medieval sources: A",
    "List of Indian expatriate footballers",
    "Xi Jinping",
    "Nick Saban",
    "List of Belgian football transfers summer 2018",
    "Foreign relations of India",
    "Tawag ng Tanghalan: New Normal",
    "List of films impacted by the COVID-19 pandemic",
    "List of sequenced animal genomes",
    "WikiLeaks",
    "Results of the 2018 Malaysian state elections by constituency",
    "List of executive actions by Joe Biden",
    "2022–23 figure skating season",
    "2021 in Ireland",
    "2013 ITF Men's Circuit (July–September)",
    "2018 New Hampshire House of Representatives election",
    "World Championship of Online Poker",
    "Timeline of Philippine history",
    "Mythology of Benjamin Banneker",
    "List of awards and nominations received by Taylor Swift",
    "Opinion polling for the 2019 Canadian federal election",
    "Agriculture in California",
    "Visa policy of Russia",
    "COVID-19 pandemic",
    "Timeline of the Russian invasion of Ukraine (12 November 2022 – 7 June 2023)",
    "List of places in the United States named after people",
    "Timeline of disability rights in the United States",
    "2019 in the United Kingdom",
    "List of Batman comics",
    "List of municipalities in Quebec",
    "Kerala",
    "2021–22 figure skating season",
    "Roger Federer career statistics",
    "List of Confederate monuments and memorials",
    "List of titular churches",
    "Records of members of parliament of the United Kingdom",
    "Charlie Baker",
    "List of people from Texas",
    "List of Italian football transfers summer 2014",
    "List of accidents and incidents involving commercial aircraft",
    "List of mass shootings in the United States in 2021",
    "Xenophobia and racism related to the COVID-19 pandemic",
    "Mueller report",
    "List of Nintendo Switch games (H–P)",
    "List of Assassin's Creed characters",
    "2021–22 PSA World Tour",
    "List of giant squid specimens and sightings (20th century)",
    "Persecution of Christians",
    "2022 deaths in the United States (January–June)",
    "List of longest-serving soap opera actors",
    "Beyoncé",
    "List of shipwrecks in 1817",
    "List of Nintendo 3DS games",
    "List of 2017 March for Science locations",
    "2020 United States Senate elections",
    "List of deaths from drug overdose and intoxication",
    "2019 in paleoentomology",
    "Electric car use by country",
    "People of the Red Orchestra",
    "Peerage of the United Kingdom",
    "History of Palestine",
    "Gianluigi Buffon",
    "List of members of the upper house of the Riksdag",
    "List of state highways in Louisiana",
    "List of Belgian football transfers summer 2017",
    "List of The Late Late Show with Craig Ferguson episodes",
    "Social media use by Donald Trump",
    "Cultural impact of Taylor Swift",
    "2018 United States House of Representatives elections",
    "Timeline of the COVID-19 pandemic in New Zealand (2021)",
    "List of early modern works on the Crusades",
    "List of Italian football transfers summer 2015",
    "2019 European Parliament election in France",
    "Marvel Cinematic Universe: Phase Four",
    "2021 Pacific typhoon season",
    "List of name changes due to the George Floyd protests",
    "List of Kalyeserye episodes",
    "List of bus routes in Queens",
    "Cultural impact of Madonna",
    "Timeline of the 2014 Venezuelan protests",
    "List of jōyō kanji",
    "Political positions of Hillary Clinton",
    "Cephalopod size",
    "Socialism",
    "List of 2019 American television debuts",
    "List of Belgian football transfers summer 2019",
    "Ralph Northam",
    "List of cities, towns and villages in North Brabant",
    "List of United States counties by per capita income",
    "List of 2017–18 NBA season transactions",
    "List of anthropogenic disasters by death toll",
    "List of events at Soldier Field",
    "List of MPs elected in the 2017 United Kingdom general election",
    "List of PAW Patrol episodes",
    "List of state routes in Pennsylvania",
    "Slavery in the United States",
    "Timeline of geopolitical changes (1900–1999)",
    "List of video game crowdfunding projects",
    "Stars and planetary systems in fiction",
    "Bibliography of the United States Constitution",
    "List of monuments and memorials removed during the George Floyd protests",
    "Iran–Iraq War",
    "List of members of the 20th Bundestag",
    "African humid period",
    "Miscegenation",
    "List of solved missing person cases: post-2000",
    "Power-to-weight ratio",
    "2011–12 ISU World Standings and Season's World Ranking",
    "2017 in video games",
    "Descendants of Ferdinand II of Aragon and Isabella I of Castile",
    "2018 Washington Nationals season",
    "Opinion polling for the 2015 Spanish general election",
    "Sub-national opinion polling for the 2016 Spanish general election",
    "List of 2017 Women's March locations",
    "List of The Simpsons guest stars (seasons 21–present)",
    "2017 Washington Nationals season",
    "List of United Kingdom Parliament constituencies (1918–1945) by region",
    "2010–11 ISU World Standings and Season's World Ranking",
    "Index of Economic Freedom",
    "COVID-19 pandemic on cruise ships",
    "Notre Dame Fighting Irish football",
    "Novak Djokovic",
    "2006 United States Senate elections",
    "List of British generals and brigadiers",
    "List of Aizoaceae of South Africa",
    "List of centaurs (small Solar System bodies)",
    "List of awards and nominations received by Game of Thrones",
    "Foreign relations of Australia",
    "List of Italian football transfers summer 2017",
    "2019 United Kingdom general election in England",
    "2018 United States gubernatorial elections",
    "2021 in video games",
    "List of 2020–21 NBA season transactions",
    "List of executive actions by Donald Trump",
    "Glossary of cue sports terms",
    "Flint water crisis",
    "List of bicycle-sharing systems",
    "2019–2020 Hong Kong protests",
    "List of foreign football players in Serbia",
    "Guns N' Roses",
    "List of driver deaths in motorsport",
    "2013 in science",
    "Foreign relations of Taiwan",
    "List of My Three Sons episodes",
    "List of songs about Oklahoma",
    "List of International Space Station spacewalks",
    "List of populated places in Colorado by county: M–Z",
    "2021 in the United Kingdom",
    "List of proclamations by Joe Biden",
    "Rafael Nadal career statistics",
    "2022 Malaysian general election",
    "2013 in arthropod paleontology",
    "List of badminton players with the most Superseries, Grand Prix, and World Tour titles",
    "List of ended Netflix original programming",
    "2015 ITF Men's Circuit (April–June)",
    "List of MPs elected in the 2019 United Kingdom general election",
    "Canada convoy protest",
    "List of Catholic dioceses (structured view)",
    "Opinion polling for the 2022 French presidential election",
    "2020 in the United States",
    "List of post offices in Colorado",
    "Results of the 2016 United Kingdom European Union membership referendum by constituency",
    "2020 in spaceflight",
    "Results of the 2020 New Hampshire House of Representatives election",
    "2015–16 ISU World Standings",
    "2012–13 ISU World Standings and Season's World Ranking",
    "List of Paramount Global television programs",
    "List of Oldham R.L.F.C. players",
    "Glossary of botanical terms",
    "2020 in paleoentomology",
    "List of films released in IMAX",
    "Impeachment inquiry against Donald Trump",
    "List of Italian football transfers summer 2018",
    "History of Germany",
    "List of Nintendo Switch games (Q–Z)"
]
